
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://ninebelowzero.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

# baseurl: /

# Google tracking id to track your visitors

google-tracking-id: "UA-35880426-4"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "en"
author: "Richard Silk"
title: "Richard Silk (ninebelowzero)"
description: "Personal website of reporter-turned-coder Richard Silk, AKA ninebelowzero."
keywords: "richard, silk, ninebelowzero, code, developer, web, javascript, ruby"
favicon: "/img/favicon.ico"
404-img: "/img/labtocat.png"

################
# Header layout #
################

black-favicon: "/img/favicon-white.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count: 1  # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 500
delete-delay: 4000
lines: # You can add HTML Tags in the Text
  - text: "We are all apprentices in a craft where no one ever becomes a master."
  - text: "Ernest Hemingway"
  - text: ""

me-img: "/img/headshop.jpg"

################
# Web app mode #
################

web-app-mode: False

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

# disqus-shortname: "panossakkos"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/ga.png"
    date: "September 2015 - December 2015"
    description: "General Assembly:<br>Web Development Immersive"
  - image: "/img/timeline/india.jpg"
    date: "February 2015 - August 2015"
    description: "Travelling<br>(India & Nepal)"
  - image: "/img/timeline/wsj.png"
    date: "January 2013 - February 2015"
    description: "Wall Street Journal:<br>Macroeconomic Reporter"
  - image: "/img/timeline/snl.png"
    date: "May 2011 - December 2012"
    description: "SNL Financial:<br>Real Estate Reporter"
  - image: "/img/timeline/altassets.png"
    date: "September 2010 - May 2011"
    description: "AltAssets.net:<br>Private Equity Reporter"
  - image: "/img/timeline/zhongwen.jpg"
    date: "October 2005 - July 2009"
    description: "Cambridge University:<br>BA in Chinese language and literature"

# First image of the Timeline

timeline-img: "/img/timeline/xmas.jpg"

###########
# Contact #
###########

email: "richardjohnsilk@gmail.com"

##################
# Social Buttons #
##################

# social:
#   - title: "facebook"
#     url: "https://facebook.com/"
#   - title: "twitter"
#     url: "https://twitter.com/"
#   - title: "github"
#     url: "https://github.com/PanosSakkos/personal-jekyll-theme"
#   - title: "bitcoin"
#     url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
#   - title: "rss"
#     url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  # Blog: 'latest-post'
  Projects: 'projects'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
